version: "3"

networks:
  localnet: {}

services:

  data:
    image: redis
    networks:
      - localnet

  server:
    build: .
    command: node_modules/.bin/nodemon --ignore modules/client server.js
    env_file: .env
    environment:
      - CACHE_URL=redis://data:6379
      - DATA_URL=redis://data:6379
      - PORT=8080
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - data
    networks:
      - localnet
    ports:
      - "8080:8080"

  # worker:
  #   build: .
  #   command: node_modules/.bin/nodemon --ignore modules/client modules/ingestLogsEveryMinute.js
  #   env_file: .env
  #   environment:
  #     - DATA_URL=redis://data:6379
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   depends_on:
  #     - data
  #   networks:
  #     - localnet
